### PR TITLE
Add some support for gcps

### PR DESCRIPTION
**Pull request by mraspaud**
This PR adds support for GCPs when the dataarray or dataset has a spatial_ref coord

### CODE REVIEW

**Comment by mraspaud** [comment]
pre-commit.ci autofix

**Comment by djhoese** [comment]
Thanks! Glad you could find time to port this over. Does this differ at all from the rioxarray implementation? If so, how?

**Comment by mraspaud** [comment]
This should be exactly the same as rioxarray, but unfortunately this is the only format I add support for. For example, support gcps from CF are not implemented.

**Comment by djhoese** [comment]
Was this documented at all in rioxarray? I'm not sure where/how would be good to document it in geoxarray.

**Comment by djhoese** [comment]
Also pre-commit does not seem happy with you.

**Comment by djhoese** [comment]
@mraspaud would you/should we consider this functionality "experimental" in any sense since, if I remember correctly, it isn't necessarily following any standard way of storing GCPs?

**Comment by djhoese** [comment]
@mraspaud What is the format of the gcps passed to `write_gcps`? GeoJSON?

I see a lot more arguments in the rioxarray method: https://corteva.github.io/rioxarray/html/rioxarray.html#rioxarray.rioxarray.XRasterBase.write_gcps

Are those unnecessary in geoxarray? Sorry if we discussed this already and I forgot.

**Comment by mraspaud** [comment]
> @mraspaud would you/should we consider this functionality "experimental" in any sense since, if I remember correctly, it isn't necessarily following any standard way of storing GCPs?

Not experimental, but not standard either as there is not standard that I'm aware of to storing GCPs.

> @mraspaud What is the format of the gcps passed to `write_gcps`? GeoJSON?
> 
> I see a lot more arguments in the rioxarray method: [corteva.github.io/rioxarray/html/rioxarray.html#rioxarray.rioxarray.XRasterBase.write_gcps](https://corteva.github.io/rioxarray/html/rioxarray.html#rioxarray.rioxarray.XRasterBase.write_gcps)
> 
> Are those unnecessary in geoxarray? Sorry if we discussed this already and I forgot.

Yes, the format it GeoJSON.
Re the other arguments: I assumed the CRS was already available in geoxarray. As for gridmapping name, I'm trying to stick to the well known `spatial_ref` for now.

**Comment by djhoese** [comment]
Judging by section 3 of https://gist.github.com/sgillies/1233327, I think the default is a WGS84 lon/lat projection (likely assumed to be EPSG:4326), but the spec mentions two important things:

1. The geojson can include a CRS.
2. If not found, it sounds like clients are expected to search any parent structures for CRS information.

I take this to mean that any future usage we have for GCPs should check and parse the GCPs for CRS information and if not found use the CRS of the DataArray/Dataset if found, otherwise default to EPSG:4326 or something equivalent.

**Comment by djhoese** [comment]
@mraspaud and I had talked a month or so ago about how this PR should be completed. One topic that came up was maybe adding the functionality for the user to provide a CRS (or to take it from the DataArray) and modify the geojson to include this CRS information as per the geojson specification. Besides not having a ton of time at the moment (on paternity leave right now), I'm not sure I like the idea of this logic being part of this `write_gcps` logic rather than as a separate utility. It seems like more responsibility/purpose in a single function/method than I'm immediately comfortable with.

@mraspaud if you don't completely disapprove/disagree of this idea then I think I'll merge this.

**Comment by mraspaud** [comment]
Sounds good, feel free to merge!

**Pull request merged**
